/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env:{
    DEV_DATABASE_URL: process.env.NEXT_PUBLIC_DEV_DATABASE_URL,
    TEST_DATABASE_URL: process.env.NEXT_PUBLIC_TEST_DATABASE_URL,
    PROD_DATABASE_URL: process.env.NEXT_PUBLIC_PROD_DATABASE_URL,
    JWT_SECRET: process.env.NEXT_PUBLIC_JWT_SECRET,
    JWT_EXPIRE_TIME: process.env.NEXT_PUBLIC_JWT_EXPIRE_TIME,
    EMAIL_VERIFICATION_SECRET: process.env.NEXT_PUBLIC_EMAIL_VERIFICATION_SECRET,
    CACHE_EXPIRE_TIME: process.env.NEXT_PUBLIC_CACHE_EXPIRE_TIME,
    MAIL_USER: process.env.NEXT_PUBLIC_MAIL_USER,
    MAIL_PASS: process.env.NEXT_PUBLIC_MAIL_PASS,
    CLOUDINARY_CLOUD_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET,
    NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL
  }
};

export default nextConfig;
